### PR TITLE
release 0.7.3

### PR DESCRIPTION
**Pull request by witekdev**
Hi 

could you please merge my changes and then make a release to Pypi?

I have been working on this ticket as part of the Plone Doc Tune-up:
https://github.com/collective/collective.developermanual/issues/95

Thanks!
Witek

### CODE REVIEW

**Comment by sdouche** [comment]
Hi,
I'm sorry for the delayed response. With your patchs, the tests seems to  be broken.

**Comment by witekdev** [comment]
Hi,
I didn't run the tests at all when I submitted my changes. I will look into this and get back to you.
Thanks!

**Comment by witekdev** [comment]
ok, first of all sorry this took so long. I suppose one can just say that life and deadlines happened. This was in the back of my mind for a while now, but I just never had a solid block of time to allocate to this till now.

ok, so the tests fail on your existing branch. 
(I ran the buildout and then ran " ./bin/test -s collective.recipe.sphinxbuilder" )
To get them to pass
I took out two lines at the end of usage.txt

These lines were removed:
    Generated script '/sample-buildout/bin/sphinx-quickstart'.
    Generated script '/sample-buildout/bin/sphinx-build'.

then the tests on your version passed (without any of my changes in them yet).

I then made some fixes to my code, updated the tests and tested my modified recipe with collective.developermanual.  Worked like it should. in the sphinx-build script: 'sphinx.main()' becomes 'sys.exit(sphinx.main())'

Please let me know once you merge my code and make a new release to pypi.
Thanks!

**Comment by sdouche** [comment]
Merged.

**Pull request closed without merging**
